### ISSUE TITLE
Question of the Day

### ISSUE THREAD

**Issue by nfearnley** [sizedev/SizeBot3AndAHalf#17]
* Users can submit questions
* These get posted to a voting channel for mods only.
* Mods react to the submissions with emotes (:voteyes:/:voteno:)
* If it gets accepted, it gets added to the pool.
* A random question (with credit) is posted to a question of the day channel every morning. (9AM EST)

## Commands

- `&submit/&question/&qotd <question>`: Submit a question for consideration.
- **mod only:** `&threshold <yes/no> <amount>`: Set the voting threshold for questions. The yes threshold is how many "yes" votes a question needs before it's added to the pool, the no threshold is how many "no" votes a question needs before it's vetoed.
- **mod only:** `&pool`: See the current pool of questions
    - `&pool remove <i>`: remove the `i`th question from the pool.
    - `&pool edit <i>`: edit the `i`th question in the pool.<sup>?</sup>

**Comment by nfearnley** [comment]
Commands:
- &qotd command

Configuration:
- qotd channel
- suggestions channel

Suggestions Channel:
- Automatically post new suggestions to channel with VoteYes and VoteNo emojis
- Track VoteYes and VoteNo reactions
- How many votes is considered accepted?
- Once accepted, add to suggestions database
- Do we allow editing by mods? (fix typos, etc)

Suggestions database:
- Suggestion text
- Suggester name
- Date used (None if not yet used)
- Votes yes
- Votes no
- Is accepted

Automatic QotD:
- Triggered daily at 9AM
- Pick a random QotD from database
- Mark the QotD as used (set date used)
- Post QotD into QotD channel

**Comment by DigiDuncan** [comment]
Should this just be its own bot?
