### ISSUE TITLE
Use discord.py prebuilt checks where possible

### ISSUE THREAD

**Issue by nfearnley** [sizedev/SizeBot3AndAHalf#69]
discord.ext.commands.has_role()
discord.ext.commands.has_permissions()
discord.ext.commands.has_guild_permissions()
discord.ext.commands.has_any_role()
discord.ext.commands.bot_has_role()
discord.ext.commands.bot_has_permissions()
discord.ext.commands.bot_has_guild_permissions()
discord.ext.commands.bot_has_any_role()
discord.ext.commands.guild_only()
discord.ext.commands.dm_only()
discord.ext.commands.is_owner()
discord.ext.commands.is_nsfw()

**Comment by DigiDuncan** [comment]
Nice.
